# -*- coding: utf-8 -*-
"""Sparrow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFXe4jnkOU-W54gwQgLM4qpAMYUQs_bc
"""

# Commented out IPython magic to ensure Python compatibility.
from math import isnan
from click import secho, echo, style
from pandas import concat, to_numeric
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import pandas as pd
from pandas import Series,DataFrame
from sklearn.datasets import load_digits
from sklearn import datasets, svm, metrics
import os
import re

#https://github.com/diegomartiperez/Sparrow-data/blob/b024ee56a59bbece9086442c52f639e85e5561b9/2021-03%20(Mar%208-)%20processed%20with%20EC%20format.xlsx
#train = pd.read_excel('/content/2021-03 (Mar 8-) processed with EC format.xlsx')
#print(train.head(10))
#train = train.drop([11],axis=1)
#url = 'https://github.com/diegomartiperez/Sparrow-data/blob/main/2021-03%20(Mar%208-)%20processed%20with%20EC%20format.xlsx'
#train = pd.read_excel(url)
#train = pd.read_excel('https://github.com/diegomartiperez/Sparrow-data/blob/main/2021-03%20(Mar%208-)%20processed%20with%20EC%20format.xlsx')

#print(train,axis=1)
#print(train.iloc[:, 45])
#print(train.iloc[0:5])
#print(train.columns.values,axis=1)
#train = train.drop.columns.values

#train= train.dropna()
#print(train.shape)
#train.replace(" ", np.nan, inplace=True)
#train= train.dropna()
#print(train.loc[178,:])


#print(train.loc[176,:].value_counts())
#print(train.shape)
#print(train["Additional analytical metadata"])
#print(train.info())
#print(train.isnull())
#print(train.head(1))
#train.dropna(subset=["Unnamed: 3"], inplace=True)
#print(train["Unnamed: 3"].shape)

#print(train.describe())
#print(train.describe())

import pandas as pd

github_raw_url = "https://github.com/diegomartiperez/Sparrow-data/raw/main/2021-03%20(Mar%208-)%20processed%20with%20EC%20format.xlsx"

df = pd.read_excel(github_raw_url)

#Delete all the rows that are fully empty
df.dropna(axis=0, how="all", inplace=True)

#Change column names to first row
df.columns = df.loc[0,:]

#Drop rows
df = df.drop(df.index[[0, 1, 2,]])


#Delete all the columns we ignore because they are empty
df.drop(df.columns[[0,11,16,62,39,40,41,42,43,44,45,63,64]], axis=1, inplace=True)

# We can do the same thing as above using dropna but on columns
df.dropna(axis=1, how="all", inplace=True)

df

"""It looks like the first row should be the column titles. Perhaps get rid of rows where "SAMPLE ID" is null. And then there will probably be some duplicates to remove as well."""

df.info()

sns.heatmap(df.isnull()) ## Checkout some of these columns with a few non-null values
## see what can be dropped and not.

